{% set name = "polyglot" %}
{% set version = "0.3.5" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  - url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
    sha256: 59d66ef5e3c166431c39cb8b7c1d02af419051352f27912f6a43981b3def16af

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem

requirements:
  host:
    - ruby
  run:
    - {{ pin_compatible('ruby', max_pin='x.x') }}

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'


about:
  home: https://rubygems.org/gems/polyglot
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The Polyglot library allows a Ruby module to register a loader for the file type associated with a filename extension, and it augments 'require' to find and load matching files.
  doc_url: http://www.rubydoc.info/gems/polyglot
  dev_url: https://github.com/cjheath/polyglot

extra:
  recipe-maintainers:
    - jdmarques
